CREATE TABLE "play" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" varchar(50),
  "id_position" integer,
  "id_nation" integer,
  "field" boolean,
  "active" boolean
);

CREATE TABLE "card" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "id_play" uuid,
  "pac" integer,
  "sho" integer,
  "pas" integer,
  "dri" integer,
  "def" integer,
  "phy" integer
);

CREATE TABLE "nation" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "acronym" varchar(3)
);

CREATE TABLE "photo" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "id_play" uuid,
  "photo" bytea
);

CREATE TABLE "position" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "acronym" varchar(3)
);

CREATE TABLE "attributes" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_position" integer,
  "pac" integer,
  "sho" integer,
  "pas" integer,
  "dri" integer,
  "def" integer,
  "phy" integer
);

CREATE TABLE "overall" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "id_play" uuid,
  "overall" integer
);

CREATE TABLE "modality" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50),
  "amount_play" int,
  "active" boolean
);

ALTER TABLE "attibutes" ADD FOREIGN KEY ("id_position") REFERENCES "position" ("id");

ALTER TABLE "overall" ADD FOREIGN KEY ("id_play") REFERENCES "play" ("id");

ALTER TABLE "photo" ADD FOREIGN KEY ("id_play") REFERENCES "play" ("id");

ALTER TABLE "card" ADD FOREIGN KEY ("id_play") REFERENCES "play" ("id");

ALTER TABLE "play" ADD FOREIGN KEY ("id_nation") REFERENCES "nation" ("id");

ALTER TABLE "play" ADD FOREIGN KEY ("id_position") REFERENCES "position" ("id");
